// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovatsngvpqaeyzdmzmvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92YXRzbmd2cHFhZXl6ZG16bXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODIwMjksImV4cCI6MjA3MDY1ODAyOX0.b0ew4ALD9p-GHw4nSVAHjqfMYd7_jZ79L2UwAH1IDdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});